/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	float a;
	float b;
};
typedef struct numbers numbers;

#define CALC_PROG 0x23451111
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  float * add_1(numbers *, CLIENT *);
extern  float * add_1_svc(numbers *, struct svc_req *);
#define SUB 2
extern  float * sub_1(numbers *, CLIENT *);
extern  float * sub_1_svc(numbers *, struct svc_req *);
#define MUlT 3
extern  float * mult_1(numbers *, CLIENT *);
extern  float * mult_1_svc(numbers *, struct svc_req *);
#define DIV 4
extern  float * div_1(numbers *, CLIENT *);
extern  float * div_1_svc(numbers *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  float * add_1();
extern  float * add_1_svc();
#define SUB 2
extern  float * sub_1();
extern  float * sub_1_svc();
#define MUlT 3
extern  float * mult_1();
extern  float * mult_1_svc();
#define DIV 4
extern  float * div_1();
extern  float * div_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
